# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  false
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    exception:
      codes:
        'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
